CREATE USER devco_app WITH ENCRYPTED PASSWORD 'devco-app-password';

GRANT CONNECT ON DATABASE "devco-db" TO devco_app;
GRANT USAGE ON SCHEMA public TO devco_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO devco_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO devco_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO devco_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO devco_app;
